name: percy components/o-grid

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
     - "components/o-grid/package.json"
     - "components/o-grid/package-lock.json"
     - "components/o-grid/origami.json"
     - "components/o-grid/main.js"
     - "components/o-grid/main.scss"
     - "components/o-grid/demos/**"
     - "components/o-grid/src/**"
  push:
    branches: main
    paths:
     - "components/o-grid/package.json"
     - "components/o-grid/package-lock.json"
     - "components/o-grid/origami.json"
     - "components/o-grid/main.js"
     - "components/o-grid/main.scss"
     - "components/o-grid/demos/**"
     - "components/o-grid/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
    - run: npm ci
    - uses: ./actions/percy/
      with:
        # To comment as the Origami Fox mascot GitHub user
        github-token: ${{secrets.ORIGAMI_FOX_ACCESS_TOKEN}}
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_GRID }}
        WORKSPACE: components/o-grid
