name: Percy components/o-visual-effects
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
     - "components/o-visual-effects/package.json"
     - "components/o-visual-effects/package-lock.json"
     - "components/o-visual-effects/origami.json"
     - "components/o-visual-effects/main.js"
     - "components/o-visual-effects/main.scss"
     - "components/o-visual-effects/demos/**"
     - "components/o-visual-effects/src/**"
  push:
    branches: main
    paths:
     - "components/o-visual-effects/package.json"
     - "components/o-visual-effects/package-lock.json"
     - "components/o-visual-effects/origami.json"
     - "components/o-visual-effects/main.js"
     - "components/o-visual-effects/main.scss"
     - "components/o-visual-effects/demos/**"
     - "components/o-visual-effects/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
    - run: npm ci
    - uses: ./actions/percy/
      with:
        # To comment as the Origami Fox mascot GitHub user
        github-token: ${{secrets.ORIGAMI_FOX_ACCESS_TOKEN}}
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_VISUAL_EFFECTS }}
        WORKSPACE: components/o-visual-effects
