name: Publish to npm as prerelease version
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # prerelease tag
jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: package sub-packages for npm
      shell: bash
      run: |
        for pkg in `ls -1d ./*/`;
        do
          cd $pkg;
          ref='${{github.ref}}'
          npm version --no-git-tag-version ${ref#refs/tags/}
          npm publish --access=public --tag prerelease
          cd -;
        done
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish meta-package to npm
      shell: bash
      run: |
        ref='${{github.ref}}'
        for pkg in `/bin/ls -1d sass-*`;
        do
          npm install -f --ignore-scripts --save-optional "@financial-times/$pkg@*";
        done
        npm version -f --no-git-tag-version ${ref#refs/tags/}
        npm publish --access=public --tag prerelease
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
